# Generated by Django 3.1.5 on 2021-01-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('number', models.IntegerField()),
                ('is_sale_off', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
