# Generated by Django 3.1.5 on 2021-01-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210114_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
