# Generated by Django 3.1.5 on 2021-01-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EGR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
