# Generated by Django 3.1.5 on 2021-01-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_agr_bgr_cgr_dgr_egr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='is_sale_off',
            new_name='is_sale',
        ),
    ]
